services:
  jwt-rust:
    image: alexroza/jwt_in_rust
    ports:
      - "8080:8080"
    networks:
      - net-api
    environment:
      DATABASE_URL: "postgres://alex:alex@postgres/postgres"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: postgres
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - net-api
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - net-api

networks:
  net-api:
    driver: bridge