name: ci-deploy
on: [push]
jobs:
  docker-config:
    runs-on: ubuntu-latest
    steps:
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up DOCKER BUILDX
        uses: docker/setup-buildx-action@v3

      - name: Login to DOCKER HUB
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: BUILD and PUSH
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: alexroza/jwt_in_rust:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
